### ISSUE TITLE
[Presentation] Milestone IV

### ISSUE THREAD

**Issue by berke-esmer-2015400021** [bounswe/bounswe2018group4#108]
Hi guys,

I am dropping some stories that we can use while we are presenting our application today. Good luck!

**@cemalaytekin posted:**
**Title:** Day One
**Posted Time**: October 20 17:23
**Mentioned Time**: June 1st, 2016
**Location**: Kilyos
**Story**: I was a lovely day.. We had just got out of preparation exam called PROFICIENCY. It was the first day of summer and we planned a night we can spend on the sands of Kilyos. We torched a light and we played guitar, we sang together. I had the chance to speak with her first time in that night. Until the dawn... So, Kilyos has a special meaning for us. If you stay in there for your preparation year as I did, do not forget that what happens in Kilyos stays in Kilyos except the love...
**Tags**: #FirstLove, #MyDearKilyos

**@cemiloz posted:**
**Title:** Secret Tunnels of Robert
**Posted Time**: October 22 11:43
**Mentioned Time**: 1950s
**Location**: Boğaziçi University
**Story**: While we were studying at Robert College, (It is known as Boğaziçi University right now) there were tunnels between every building of faculties. Professors would get angry when we use them but they wouldn't lock them anyway. They were very useful.
**Tags**: #RobertCollege, #SecretTunnels, #Classified

**@mehmetdrd posted:**
**Title:** High School of Graduation
**Posted Time**: October 25 14:21
**Mentioned Time**: 2015
**Location**: Mihrabat Korusu
**Story**: I was the organiser of our high school graduation party. When the duty was offered to me, I volunteered cheerfully. I looked over many places and I decided to book Mihrabat Korusu in Beykoz. There was a very beautiful scene of Bosphorus Bridge and the sea. We ate, we had fun. Everybody was grateful.
**Tags**: #HighSchoolGraduation, #Party

**@BerkeTheTechNerd posted:**
**Title:** GaziantepFest
**Posted Time**: October 28 10.02
**Mentioned Time**: September 2018
**Location**: Gaziantep
**Story**: In the first week of September, we went to Gaziantep all together with 10 other friends. It was a week that we ate all the time continously. The food was awesome! I can't tell whether I went there to travel or eat lol...
**Tags**: #GaziantepFest, #DeliciousFood

**Comment by berke-esmer-2015400021** [comment]
The last one can be used for new memory posting.

**Comment by berke-esmer-2015400021** [comment]
**Presentation Scheme**

1. Welcome
2. Brief information on the project
3. What we have done so far. [Each team]
4. Demo presentation [Each team]
5. Q&A

**Comment by dilaragokay** [comment]
Congratulations for the presentation Beavers!
