### ISSUE TITLE
[Frontend] Connection of profile page to backend

### ISSUE THREAD

**Issue by dilaragokay** [bounswe/bounswe2018group4#111]

**Comment by busrahcirit** [comment]
I tried different methods to get the user's information. I have struggled with some problems like getting "token" field on login-page. I made it work yesterday but  I changed the branch without committing my code and I have to start from scratch.

**Comment by busrahcirit** [comment]
I am working on getting user's information. ComponentDidMount() and render() methods are working at the same time. https://reactjs.org/docs/react-component.html helps me for understanding my problems on the page. Be careful!

**Comment by busrahcirit** [comment]
Connection is completed except the profile picture. The profile picture will be handled with edit profile page function.
