### ISSUE TITLE
Research W3C Web Annotation Data Model.

### ISSUE THREAD

**Issue by ege-saygili-2015405147** [bounswe/bounswe2018group4#116]
Since we will include annotations in our projects, we need to learn about W3C Web Annoation Data Model. Here are some links that may help:

https://www.w3.org/annotation/
https://www.w3.org/TR/2017/REC-annotation-model-20170223/
https://www.w3.org/TR/2017/REC-annotation-protocol-20170223/

**Comment by ege-saygili-2015405147** [comment]
There seems to be some examples of annotations. Maybe thay can be of help.
https://github.com/SWE574-Groupago/heritago/issues/16

**Comment by berke-esmer-2015400021** [comment]
I will look into them. Thanks!

**Comment by dilaragokay** [comment]
This issue closes as annotation is implemented.
