### ISSUE TITLE
[Backend] Recommendations

### ISSUE THREAD

**Issue by ege-saygili-2015405147** [bounswe/bounswe2018group4#120]

**Comment by dilaragokay** [comment]
How can frontend send request for getting recommendations?

**Comment by ege-saygili-2015405147** [comment]
`http://ec2-18-234-162-48.compute-1.amazonaws.com:8000/post/memory_recommendations/`

You can use this URL to send request for recommendations with GET method. You also have to send the user's token as Authorization header.

**Comment by berke-esmer-2015400021** [comment]
`http://ec2-18-234-162-48.compute-1.amazonaws.com:8000/post/memory_recommendations/
`
This url retursn 0 length result. Is there a problem?
