### ISSUE TITLE
[Backend] Search

### ISSUE THREAD

**Issue by yusufbaspinar** [bounswe/bounswe2018group4#121]

**Comment by yusufbaspinar** [comment]
1.2.1. Users shall be able to search memories.
1.2.1.1. Users shall be able to search by text.
1.2.1.2. Users shall be able to search by location.
1.2.1.3. Users shall be able to search by mentioned time.
1.2.1.4. Users shall be able to search by tag.
1.2.1.5. Users shall be able to search by posting time.
1.2.2. Users shall be able to search users by username.

We should work on these requirements

**Comment by EmreKc** [comment]
Search users by username function has been implemented.

**Comment by ege-saygili-2015405147** [comment]
Memory Search has been implemented.

`post/memory_search/<search-text>/`

This URL can be used with get method. Also, the user's token is needed as the Authorization header.
