### ISSUE TITLE
[Presentation] Milestone V

### ISSUE THREAD

**Issue by busrahcirit** [bounswe/bounswe2018group4#125]
We need to prepare and deliver our milestone report today.

**Comment by busrahcirit** [comment]
This is the link for new milestone report. https://github.com/bounswe/bounswe2018group4/wiki/Milestone-5

**Comment by berke-esmer-2015400021** [comment]
I have filled most of the basic information columns. The rest of the report belongs to the individual contributions. It would be nice if you fill those blanks.

**Comment by dilaragokay** [comment]
Looks good, we're on track! 💪🏽 I added Related Requirements as well as my contributions.

**Comment by berke-esmer-2015400021** [comment]
This documentation has already been delivered to the customer.
