### ISSUE TITLE
Milestone 2 report

### ISSUE THREAD

**Issue by uskudarli** [bounswe/bounswe2018group4#137]
General response to Milestone 2 lessons learned.

https://github.com/bounswe/bounswe2018group4/wiki/Milestone-5

**Comment by uskudarli** [comment]
The purpose of **milestone** reports are to reflect on status and development process management in specific manners, so as to take intermediate actions to mitigate in order to take corrective actions.

I believe you would benefit from focusing on:

- customer response during demo (especially if there is some concern)
- the state of connection between front end/back end
- loss of functionality present in earlier demos (the loss during presentation)
- specific issues of management (there was mention that there were some issues, but they were not described. Nor were there any actions specified to respond to these issues)

**Comment by uskudarli** [comment]
I look forward to your reflections on your process. The meeting today was beneficial. Thanks.

**Comment by kerata** [comment]
So this is still open?

**Comment by berke-esmer-2015400021** [comment]
Sorry. It is just left open. We actually discussed our customer’s feedback after the milestone 2.
