### ISSUE TITLE
[Frontend]Comment & Vote 

### ISSUE THREAD

**Issue by EmreKc** [bounswe/bounswe2018group4#140]

**Comment by dilaragokay** [comment]
Relevant requirements:

## 1.5.1. Comment & Like
### 1.5.1.1. Comment
* 1.5.1.1.1. User should be able to comment on memories.
* 1.5.1.1.2. User should be able to add subcomments on comments.
* 1.5.1.1.3. User should be able to add multimedia items in comments.
### 1.5.1.2. Like
* 1.5.1.2.1. User should be able to like posts.
* 1.5.1.2.2. User should be able to like comments.
* 1.5.1.2.3. User should be able to see the number of likes of a post or comment.

**Comment by dilaragokay** [comment]
User can like a memory: #168

**Comment by dilaragokay** [comment]
User can view memories: #176

**Comment by dilaragokay** [comment]
User can comment a memory: #181.
