### ISSUE TITLE
[Frontend] Post Recommendation

### ISSUE THREAD

**Issue by EmreKc** [bounswe/bounswe2018group4#151]

**Comment by busrahcirit** [comment]
Relevant Requirements:
## 1.4. Recommendation
* **1.4.1.** Registered user shall be able to see tag based recommendations.
* **1.4.2.** Registered user shall be able to see trending post based recommendations.

**Comment by ege-saygili-2015405147** [comment]
**1.4.1**

`post/memory_recommendations/`

This URL can be used with GET method to list recommendations according to the tags of the memories the user has posted. You also have to send the user's token as Authorization header to make this request.

**1.4.1**

`post/top_memories/`

This URL can be used to list top 20 most liked memories in the platform.

**Comment by dilaragokay** [comment]
Thanks! Frontend displays top memories.
