### ISSUE TITLE
[Frontend] Show locations in pinned map  

### ISSUE THREAD

**Issue by ege-saygili-2015405147** [bounswe/bounswe2018group4#158]

**Comment by busrahcirit** [comment]
Relevant requirements:
1.5.3.3. Location
     1.5.3.3.1. Registered  user shall be able to add a location to the memory.

**Comment by dilaragokay** [comment]
It looks like we can use [Maps Embed API](https://developers.google.com/maps/documentation/embed/start) for a single location and [Maps Static API](https://developers.google.com/maps/documentation/maps-static/intro#Paths) for picking a route. I will go over the steps to use those.

**Comment by ege-saygili-2015405147** [comment]
What fields will you need for location? We will edit our location model according to your needs.

We thought a location name, coordinates and possibly a radius(if we need to show an area) might be enough but we'd like to be sure.

**Comment by busrahcirit** [comment]
One location is handled. Path is in progress.
