### ISSUE TITLE
[Android] Creating comment page data transfer

### ISSUE THREAD

**Issue by yunusdemirci** [bounswe/bounswe2018group4#167]
Pages are ready, but data transfer from memory adapter to commit page is not satisfied

**Comment by berke-esmer-2015400021** [comment]
How is it going?

**Comment by berke-esmer-2015400021** [comment]
I completed this issue's part. 

What I did was essentially something easy and we were missing it. I created a listener in the memory adapter which is then implemented in the memory activity. Afterwards, I created a function to pass a memory item into memory activity when the comment button is clicked in a memory. Thus, I set a onclick listener to the button comments.

Then, I created the fragment in memory activity. I passed the memory parameter using Bundles. Bundles are easy to carry data between activities and fragments. 

At the end, I connected the fragment with its api function

**Comment by berke-esmer-2015400021** [comment]
The PR is open. You can see it [here](https://github.com/bounswe/bounswe2018group4/pull/177)
