### ISSUE TITLE
Milestone VI Presentation

### ISSUE THREAD

**Issue by berke-esmer-2015400021** [bounswe/bounswe2018group4#174]
As you all know, this is going to be our final demo. All presentation related communication can take place under this issue.

We are going to need
- Some user stories to present on functions
- Some user stories to present functionality of annotations
- A planning of presentation.

Thus a lot of content is going to be needed.

**Comment by dilaragokay** [comment]
I think we should meet ASAP for discussing annotations.

**Comment by berke-esmer-2015400021** [comment]
We need a lot of user stories for this milestone. 
If we have more than 10 stories, it would be perfect!
Those are for front-end and android presentations. And some of them needs to be in the system.

**Comment by dilaragokay** [comment]
Done! 🎉
