### ISSUE TITLE
[Backend | Frontend | Android] Advanced Location field added to User Profile

### ISSUE THREAD

**Issue by ege-saygili-2015405147** [bounswe/bounswe2018group4#185]
The field's name is **advanced_location**. Its type is **PointLocation**.

Class **PointLocation** contains name and coordinates:
* location_name --> contains the location's name
* location_coordinate_latitude --> the latitude of the location (enlem)
* location_coordinate_longitude --> the longitude of the location (boylam)

However, the old field **location** still exists, so hopefully this update will not cause any problems. You can still use the old **location** field as you please. So, you need not hurry to implement **advanced_location**. However, ideally, we will use **advanced_location** instead of **location**.

**Comment by berke-esmer-2015400021** [comment]
Thanks!
