### ISSUE TITLE
Type error received when trying to create memory

### ISSUE THREAD

**Issue by uskudarli** [bounswe/bounswe2018group4#195]
I was on my profile page (uskudarli).

When  I try to create a memory I get the following bug:

×
TypeError: file is undefined
componentWillUnmount
src/views/CreateMemoryPage/CreateMemoryPage.jsx:79

  76 |        const {files} = this.state;
  77 |        for (let i = files.length; i >= 0; i--) {
  78 |            const file = files[i];
> 79 |            URL.revokeObjectURL(file.preview);
  80 |        }
  81 |    }
  82 | 

callComponentWillUnmountWithTimer
node_modules/react-dom/cjs/react-dom.development.js:14602
callCallback
node_modules/react-dom/cjs/react-dom.development.js:145
invokeGuardedCallbackDev
node_modules/react-dom/cjs/react-dom.development.js:195
invokeGuardedCallback
node_modules/react-dom/cjs/react-dom.development.js:248
safelyCallComponentWillUnmount
node_modules/react-dom/cjs/react-dom.development.js:14609
commitUnmount
node_modules/react-dom/cjs/react-dom.development.js:14841
unmountHostComponents
node_modules/react-dom/cjs/react-dom.development.js:15150
commitDeletion
node_modules/react-dom/cjs/react-dom.development.js:15181
commitAllHostEffects
node_modules/react-dom/cjs/react-dom.development.js:15852
callCallback
node_modules/react-dom/cjs/react-dom.development.js:145
invokeGuardedCallbackDev
node_modules/react-dom/cjs/react-dom.development.js:195
invokeGuardedCallback
node_modules/react-dom/cjs/react-dom.development.js:248
commitRoot
node_modules/react-dom/cjs/react-dom.development.js:16040
completeRoot
node_modules/react-dom/cjs/react-dom.development.js:17463
performWorkOnRoot
node_modules/react-dom/cjs/react-dom.development.js:17391
performWork
node_modules/react-dom/cjs/react-dom.development.js:17295
performSyncWork
node_modules/react-dom/cjs/react-dom.development.js:17267
interactiveUpdates$1
node_modules/react-dom/cjs/react-dom.development.js:17558
interactiveUpdates
node_modules/react-dom/cjs/react-dom.development.js:2208
dispatchInteractiveEvent
node_modules/react-dom/cjs/react-dom.development.js:4913
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.

**Comment by dilaragokay** [comment]
Thank you for pointing out this issue. I just figured out the reason.

In `resources/material_kit/src_views/CreateMemoryPage/CreateMemoryPage.jsx`, the following line was causing trouble:

> 77 |            for (let i = files.length; i >= 0; i--) {

When there is no file uploaded, files.length is 0. Since 0>=0, 

> 79 |            URL.revokeObjectURL(file.preview);

is called even when there is no file and raises TypeError.

I changed this line (77) and pushed changes to `master`.
