### ISSUE TITLE
New registration verification via email goes to REST calls

### ISSUE THREAD

**Issue by uskudarli** [bounswe/bounswe2018group4#196]
I received an email to confirm my registration. When I try to confirm I go to a page such as:

      Verify Email 

Verify Email

GET /auth/verify_email/?uh=9e700ea20fd707d1689940585b9aae9ff082f550

HTTP 200 OK
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "status": "ok"
}

Screenshot

![image](https://user-images.githubusercontent.com/1347035/50601074-32319580-0ec4-11e9-812c-7bd66a615b8a.png)

**Comment by EmreKc** [comment]
It was solved. After verify your email, you will be redirected to frontend login page
