### ISSUE TITLE
Everybody must edit their avatar on the readme.md

### ISSUE THREAD

**Issue by alaattin-cerrah-2014400126** [bounswe/bounswe2018group4#22]
You need to change you avatar in your profil page and wait for a few minutes for the Github to apply the change across their databeses.

You can check your name and unassing yourself after you did your part.

- [x] Dilara Gökay
- [x] Abdülkadir Aslan
- [x] Yusuf Başpınar
- [x] Alaattin Kaan Cerrah
- [x] Büşra Hilal Cirit
- [x] Yunus Emre Demirci
- [x] Berke Esmer
- [ ] Egemen Kaplan
- [x] Emre Koç
- [x] Yunus Ege Saygılı

**Comment by berke-esmer-2015400021** [comment]
Hey, it would be awesome if all remaining avatars are completed!

**Comment by yunus-demirci-2016400258** [comment]
If fair for you @busrahcirit . We can close
