### ISSUE TITLE
We can discuss about wiki page in this issue.

### ISSUE THREAD

**Issue by alaattin-cerrah-2014400126** [bounswe/bounswe2018group4#23]

**Comment by berke-esmer-2015400021** [comment]
I am deleting the members from the homepage since it exists on the sidebar. I think it is more clean with just a picture.

**Comment by dilaragokay** [comment]
There are a lot of information about team in wiki page and README. It might be more explanatory for users to encounter information about project too.

**Comment by berke-esmer-2015400021** [comment]
I added some information highlighting the features of our application. Another review is needed!
