### ISSUE TITLE
The project plan is our next step

### ISSUE THREAD

**Issue by berke-esmer-2015400021** [bounswe/bounswe2018group4#25]
Dilara and Büşra will work on this.

**Comment by dilaragokay** [comment]
We discussed with Büşra about the structure of project plan. Plan for CMPE352 is available [here](https://github.com/bounswe/bounswe2018group4/wiki/Project-Plan).

**Comment by berke-esmer-2015400021** [comment]
Should we add things that we will do in cmpe451 into the plan? I thought this was also asked us to do.

**Comment by busrahcirit** [comment]
I will add it soon.

**Comment by busrahcirit** [comment]
I added the cmpe451 plan. Waiting for review.

**Comment by berke-esmer-2015400021** [comment]
It looks nice!
