### ISSUE TITLE
Creating a poll for meeting time

### ISSUE THREAD

**Issue by dilaragokay** [bounswe/bounswe2018group4#29]

**Comment by EmreKc** [comment]
[I have created a poll for meeting hours ](https://docs.google.com/forms/d/e/1FAIpQLSc69tfvoPfDifiCGg_tn8HlxRiZF8BdfdYmwfysUPmSZ5_g5g/viewform?usp=sf_link)

**Comment by EmreKc** [comment]
[You can reach the poll here](https://docs.google.com/forms/d/e/1FAIpQLSc69tfvoPfDifiCGg_tn8HlxRiZF8BdfdYmwfysUPmSZ5_g5g/viewform?usp=sf_link)
