### ISSUE TITLE
Project Requirements will be revisited.

### ISSUE THREAD

**Issue by yusufbaspinar** [bounswe/bounswe2018group4#33]
As first milestone reached Project Requirements will be enhanced this week.

**Comment by berke-esmer-2015400021** [comment]
Well, I am taking Non-Functional Requriements part.

**Comment by berke-esmer-2015400021** [comment]
I have done my part. You can review it.

**Comment by yusufbaspinar** [comment]
I have done some alternations and reviewed the Project Requirement section. It is all looking good. Thanks for all who made great deal of efford to make such a brilliant thing to achieve. And of course thank to the academy who honoured me with this wonderful award. I am speechless. Thank you very so much. Global warming is real. Peace.
