### ISSUE TITLE
Need review of user scenarios. Also need suggestions about persona photos.

### ISSUE THREAD

**Issue by alaattin-cerrah-2014400126** [bounswe/bounswe2018group4#36]

**Comment by dilaragokay** [comment]
Scenarios look good. We may use free stock photos for persona photos.

**Comment by alaattin-cerrah-2014400126** [comment]
I have added stock photos for personas. If it looks ok then the issue can be closed.

**Comment by dilaragokay** [comment]
Photos are good. 

I think this sentence could have been clearer: Trying to kill the time that he was at work while he was working.
