### ISSUE TITLE
First part of HW6: Class Diagram

### ISSUE THREAD

**Issue by berke-esmer-2015400021** [bounswe/bounswe2018group4#41]
We are going to publish our class diagram of application Saturday, 23.55
Related discussion can be gathered here...

**Comment by dilaragokay** [comment]
[Class diagram](https://github.com/bounswe/bounswe2018group4/blob/master/resources/diagrams/v1_userclass.png) is uploaded and wiki page is edited accordingly.

**Comment by berke-esmer-2015400021** [comment]
Looks nice!

**Comment by berke-esmer-2015400021** [comment]
Change needed : A link to homepage from system

**Comment by dilaragokay** [comment]
Added the link and changed the diagram according to sequence diagram. New diagram is [here](https://github.com/bounswe/bounswe2018group4/blob/master/resources/diagrams/v2_userclass.png).

**Comment by yunus-demirci-2016400258** [comment]
Maybe "date" and "time" can combine
