### ISSUE TITLE
Adding API files

### ISSUE THREAD

**Issue by EmreKc** [bounswe/bounswe2018group4#61]
You can add your codes(as a method) written by using twitter API into views.py that is under the  TwitterAPI_Project/allAPIs.But first,you need to pull master branch into your local computer then  you can add your codes.

- [x] Busra Cirit

- [x] Dilara Gokay

- [ ] Egemen Kaplan

- [x] Alaattin Cerrah

- [x] Emre Koc

- [x] Yunus Demirci

- [x] Berke Esmer

- [x] Ege Saygili

- [x] Abdulkadir Aslan

- [x] Yusuf Baspinar

**Comment by yunus-demirci-2016400258** [comment]
I just add function. I think we can write  common tokens above the functions.

**Comment by alaattin-cerrah-2014400126** [comment]
I added my function. I put tokens into another file named keys.py.
