### ISSUE TITLE
Project Requirements will be reviewed.

### ISSUE THREAD

**Issue by berke-esmer-2015400021** [bounswe/bounswe2018group4#80]
A new development term is ahead of us. 

We are going to review what we thought should be in the requirements in the last term. We are going to improve them to make things more realistic.

[Here](https://github.com/bounswe/bounswe2018group4/wiki/Project-Requirements), you can reach to requirements.

**Comment by berke-esmer-2015400021** [comment]
I deleted an item because of the duplication. There were two same lines stating there shall be descriptions in memories.

**Comment by dilaragokay** [comment]
Should we increase the [response time](https://github.com/bounswe/bounswe2018group4/wiki/Project-Requirements#21-performance)? I don't know how tough it would be to make it 2 s so maybe we can set it to be at most 5 s.

**Comment by dilaragokay** [comment]
According to the latest customer feedback, the whole structure in functional requirements needs to change. Requirements will be structured not by users but by functionalities. The assignment of functionalities that need to be written and assignees are as follows,
* Glossary update - Yunus Emre Demirci
* Login & registration - Büşra Hilal Cirit
* Search - Ege Saygılı
* Follow - Dilara Gökay
* Recommendation - Berke Esmer
* Comment & like, annotation - Kadir Aslan
* Story, title - Kaan Cerrah
* Time, location - Emre Koç
* Multimedia, tag - Yusuf Başpınar

**Comment by dilaragokay** [comment]
> * We will need to define the meaning of popularity that we used for recommendations.

How about popularity = number of likes?

**Comment by dilaragokay** [comment]
Is this resolved?

**Comment by berke-esmer-2015400021** [comment]
Yeap! Our requirements are finalized. Issue is closed.
