### ISSUE TITLE
Project Plan is needed to get on track.

### ISSUE THREAD

**Issue by berke-esmer-2015400021** [bounswe/bounswe2018group4#81]
We need to see what is ahead of us in the near future to make things smooth. A project plan is what we exactly need.

**Comment by dilaragokay** [comment]
See the poject plan for CMPE451 [here](https://drive.google.com/file/d/13lzWcEO-VgSYD9F22C29TCPIxgeaicU0/view?usp=sharing).

**Comment by dilaragokay** [comment]
This plan is still subject to change. I assign this issue to everyone as it affects every member of the team.

**Comment by dilaragokay** [comment]
[Project plan](https://github.com/bounswe/bounswe2018group4/blob/master/resources/project_plan/Project_Plan_451.pdf) is updated based on the suggestions discussed offline.
