### ISSUE TITLE
Annotation based user stories are needed.

### ISSUE THREAD

**Issue by berke-esmer-2015400021** [bounswe/bounswe2018group4#82]
Our customer has asked for three different example stories for the use of annotations in our application. This has to be done until October 5th.

**Comment by berke-esmer-2015400021** [comment]
You can find the page [here](https://github.com/bounswe/bounswe2018group4/wiki/Annotation-Stories).

**Comment by dilaragokay** [comment]
* Annotation scenarios look good and well-detailed!
* Can you specify how users annotate story? For example, Esra might highlight a phrase in the story.
* Story 1,2,3 -> Scenario 1,2,3 might be more clear.
* The link in the most recent comment seems broken.

**Comment by berke-esmer-2015400021** [comment]
You are right, I made the changes as in the examples you gave.
Also, the link is fixed now! :+1:
