### ISSUE TITLE
[Backend] Login & Register Urls

### ISSUE THREAD

**Issue by EmreKc** [bounswe/bounswe2018group4#85]
- Create Register Url
      - Request 
               {"first_name",
                "last_name",
                "email",
                "username",
                "password"
              }
       - Response 
             {"token",
              "user":{
                         "id",
                         "first_name",
                         "last_name",
                         "username",
                         "email"
                        }
             }
- Create Login Url 
        - Request {
                         "username",
                         "password"
                        }
       - Response 
             {"token",
              "user":{
                         "id",
                         "first_name",
                         "last_name",
                         "username",
                         "email"
                        }
             }

**Comment by dilaragokay** [comment]
Is this resolved?

**Comment by yusufbaspinar** [comment]
It is resolved.
