### ISSUE TITLE
[Frontend - Backend]Fields of a post 

### ISSUE THREAD

**Issue by busrahcirit** [bounswe/bounswe2018group4#95]
We need to decide the fields of a post. We have to consider the functions and look at the class diagram we did. (https://github.com/bounswe/bounswe2018group4/wiki/Class-Diagram)

**Comment by dilaragokay** [comment]
The following fields might work. I'm basically retyping class diagram and I restructured it a bit according to the most recent project requirements.
* memoryId
* owner
* publishedTime
* numLikes
* numDislikes
* comment[]
* memoryItem[]
   * multimedia[]
   * tag[]
   * location (structure of this data depends on resolution)
   * story
   * mentionedTime (structure of this data depends on resolution)

**Comment by dilaragokay** [comment]
Resulting fields are:

* "id"
* "owner"
*  "posting_time"
* "title"
*  "texts"
* "multimedia"
* "tags"
* "numlikes"
* "comments"
* "numcomments
* "location"
* "mentioned_time"
* "liked_users"
